deploy front and back end

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,67 +1,73 @@
 version: 2.1
 
 commands:
-  install-ansible:
-    description: Install ansible
+
+  install_awscli:
+    description: Install AWS cli
     steps:
       - run:
-          name: Install-ansibles
+          name: Install AWS cli
+          command: |
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+  install_nodejs:
+     description: Install Node.js 13
+     steps:
+      - run:
+          name: Install Node.js 13
+          command: |
+            curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
+            sudo apt install -y nodejs
+  install_ansible:
+    description: Install Ansible
+    steps:
+      - run:
+          name: Install Ansible
           command: |
             sudo apt update
             sudo apt install software-properties-common -y
             sudo add-apt-repository --yes --update ppa:ansible/ansible
             sudo apt install ansible -y
-  
-  install-nodejs:
-    description: Install nodejs
-    steps:
-    - run:
-        name: Install-nodejs
-        command: |
-          curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
-          sudo apt install -y nodejs
-
-  install-awscli:
-    description: Install AWS CLI V2
-    steps:
-      - run:
-          name: Install_AWS_CLI_V2
-          command: |
-            sudo apt-get update && sudo apt-get install -yy less
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
+      # Add parameter here   
       workflow_id:
         default: "${CIRCLE_WORKFLOW_ID:0:7}"
         type: string
+
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
+            # Your code here
+            aws s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive
             aws cloudformation delete-stack --stack-name "udapeople-backend-<<parameters.workflow_id>>"
             aws cloudformation delete-stack --stack-name "udapeople-frontend-<<parameters.workflow_id>>"
             
-  revert-migrations: 
+            
+  revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
+      # Add parameter here 
       workflow_id:
         default: "${CIRCLE_WORKFLOW_ID:0:7}"
-        type: string     
+        type: string
+    
     steps:
       - run:
           name: Revert migrations
           when: on_fail
           command: |
-            SUCCESS=$(curl --insecure  https://kvdb.io/9eyMiS2a3HKNjdN2tqeAPB/migration_<< parameters.workflow_id >>)
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS=$(curl --insecure "https://kvdb.io/AfxCuACWvcrzuTJxyg9dLE/migration_<<parameters.workflow_id>>")
             if(( $SUCCESS==1 )); 
             then
               cd ~/project/backend
               npm install
-              npm run migration:revert
+              npm run migrations:revert
             fi
 jobs:
   build-frontend:
@@ -70,16 +76,17 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-deps]
+          keys: [frontend-build]
       - run:
           name: Build front-end
           command: |
+            # Your code here
             cd frontend
             npm install
             npm run build
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-deps
+          key: frontend-build
 
   build-backend:
     docker:
@@ -87,7 +94,7 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-deps]
+          keys: [backend-build]
       - run:
           name: Back-end build
           command: |
@@ -96,104 +103,115 @@ jobs:
             npm run build
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-deps
+          key: backend-build
 
   test-frontend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      ## Restore from cache
       - restore_cache:
-          keys: [frontend-deps]
+          keys: [frontend-test]
+      # Your job code here
       - run:
-          name: Test front-end
+          name: Frontend test
           command: |
             cd frontend
             npm install
             npm run test
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-deps
-                
+          key: frontend-test
+
   test-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      ## Restore from cache
       - restore_cache:
-          keys: [backend-deps]
+          keys: [backend-test]
+      # Your job code here
       - run:
-          name: Back-end test
+          name: Backend test
           command: |
             cd backend
             npm install
             npm run test
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-deps           
+          key: backend-test
+
   scan-frontend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      # Restore from cache
       - restore_cache:
-          keys: [frontend-deps]
+          keys: [frontend-scan]
+      # Your job code here
       - run:
-          name: Scan front-end
+          name: Frontend-Scan
           command: |
             cd frontend
             npm install
             npm audit fix --audit-level=critical --force
-            npm audit fix -- force
+            # npm install oauth-sign@^0.9.0
+            npm audit --audit-level=critical
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-deps
-  
+          key: frontend-scan
+
   scan-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      # Restore from cache
       - restore_cache:
-          keys: [backend-deps]
+          keys: [backend-scan]
+      # Your job code here
       - run:
-          name: Scan back-end
+          name: Backend-Scan
           command: |
             cd backend
             npm install
             npm audit fix --audit-level=critical --force
-            npm audit fix -- force
             npm audit --audit-level=critical
       - save_cache:
           paths: [backend/node_modules]
-          key: backend-deps
-      
+          key: backend-scan
+
+
 
   deploy-infrastructure:
     docker:
-      - image: amazon/aws-cli
+      - image: cimg/base:stable
     steps:
       - checkout
-      - run:
-          name: install dependecies
-          command: |
-            yum install -y tar gzip
+      - install_awscli
+      # - run: yum -y install tar gzip 
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
+              --tags project=udapeople \
               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
-              --tags project=udapeopleback
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
+              
+            echo ${CIRCLE_WORKFLOW_ID:0:7}
+              
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
+              --tags project=udapeople \
               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
-              --tags project=udapeoplefront
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  
               
       - run:
           name: Add back-end ip to ansible inventory
@@ -202,32 +220,35 @@ jobs:
             cat inventory.txt
             aws ec2 describe-instances \
             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --output text --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" >> inventory.txt
+            --output text --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} >> inventory.txt
             cat inventory.txt
-            # export BACKEND_IP=$(aws ec2 describe-instances \
-            # --query 'Reservation[*].Instances[*].PublicIpAddress' \
-            # ---filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-            # --output text )
-            # echo BACKEND_IP            
+             export BACKEND_IP=$(aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
+            --output text 
+            )
+            echo ${BACKEND_IP}
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      - destroy-environment
-            
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment 
 
   configure-infrastructure:
     docker:
+      # Docker image here that supports Ansible
       - image: cimg/base:stable
     steps:
       - checkout
       - add_ssh_keys:
           fingerprints:
-            - "ad:c0:a2:a6:7d:1b:f3:dc:0b:5f:88:8d:4d:76:6a:57"
+            - "7c:94:37:dc:a6:23:58:07:35:9d:7e:c9:84:25:81:cc"
       - attach_workspace:
           at: ~/
-      - install-ansible
-      - install-awscli
+    
+      - install_ansible    
+      - install_awscli
       - run:
           name: Configure server
           command: |
@@ -236,12 +257,15 @@ jobs:
             ansible-playbook -i inventory.txt configure-server.yml
       - destroy-environment
 
+       # Here's where you will add some code to rollback on failure
+
+
+
   run-migrations:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - install-awscli
       - run:
           name: Run migrations
           command: |
@@ -253,14 +277,11 @@ jobs:
           command: |
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-              curl --insecure https://kvdb.io/9eyMiS2a3HKNjdN2tqeAPB/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+             curl --insecure https://kvdb.io/AfxCuACWvcrzuTJxyg9dLE/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
             fi
-      - destroy-environment
-      - revert-migrations
+      - destroy-environment 
+      - revert-migrations     
 
-          
-
- 
   deploy-frontend:
     docker:
       - image: cimg/base:stable
@@ -337,40 +358,47 @@ jobs:
       - destroy-environment
       - revert-migrations
 
+
+
   smoke-test:
     docker:
       - image: cimg/base:stable
     steps:
       - checkout
-      - install-nodejs
-      - install-awscli
+     
+      - install_nodejs
+      - install_awscli
       - run:
-          name: Get backend url
+          name: Backend smoke test.
           command: |
-            export BACKEND_IP=$(aws ec2 describe-instances \
-            --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --output text --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}")
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-            if curl -v ${API_URL}/api/status | grep "ok"
-            then
-                echo 0
-            else
-                echo 1
-            fi
+              BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+                --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+                --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                --output text)
+              export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+              echo ${BACKEND_PUBLIC_IP}
+              echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+              echo ${API_URL}
+              if curl -s $API_URL/api/status | grep "ok"
+              then
+                exit 0
+              else
+                exit 1
+              fi
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com/#/employees"            
-            echo ${URL} 
-            if curl -v ${URL} | grep "Welcome"
-            then
-              echo 1
-            else
-              echo 1
-            fi
-       
-       
+              FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+              echo $FRONTEND_WEBSITE
+              if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+              then
+                exit 0
+              else
+                exit 1
+              fi
+      - destroy-environment
+      - revert-migrations
+
 
 #   cloudfront-update:
 #     docker:
